import '@/features/popup/popup'
import '@/features/inputMask'

import 'layout/header/header.js'
import 'layout/footer/footer.js'

import 'components/specialists/specialists'
import 'components/gallery/gallery'
import 'components/main-hero/main-hero'
import 'components/solutions/solutions.js'
import 'components/seo/seo.js'
import 'components/reviews/reviews'
import 'components/our-clients/our-clients.js'
import 'components/projects/projects.js'
import 'components/about-company/about-company.js'
import 'components/software/software.js'
import 'components/project-list/project-list.js'
import 'components/equipment/equipment.js'
import 'components/articles/articles.js'
import 'components/other-sales/other-sales.js'

import 'pages/about/certificates/certificates.js'
import 'pages/contacts/components/contacts-map.js'

import 'features/fancybox'
